# AWS CodeBuild buildspec for secrets detection
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting secrets detection..."
      - apt-get update && apt-get install -y git
      - pip3 install detect-secrets

  build:
    commands:
      - echo "Scanning for secrets with detect-secrets..."
      - detect-secrets scan --baseline .secrets.baseline . || true
      - echo "Running TruffleHog scan..."
      - pip3 install truffleHog3 || pip3 install trufflehog
      - |
        truffleHog3 . --output json 2>/dev/null > truffleHog-results.json || \
        trufflehog filesystem . --json > truffleHog-results.json 2>/dev/null || true
      - echo "Secrets scan completed"

  post_build:
    commands:
      - echo "Processing secrets detection results..."
      - if [ -f truffleHog-results.json ]; then wc -l truffleHog-results.json; fi

artifacts:
  files:
    - truffleHog-results.json
    - .secrets.baseline
    - '**/*'
  name: SecretsArtifacts

reports:
  secrets-report:
    files:
      - truffleHog-results.json
    file-format: 'JSON'
